import { generateDeterministicResponse, normalizeAiResponse } from '../utils/responseGenerator'

const SYSTEM_PROMPT = `You are a disaster-response planning assistant.

You are given structured analysis generated by a geospatial disaster-intelligence system.

Do not invent facts. Do not modify numerical values. Do not calculate new risk scores. Do not claim information is real-time unless explicitly provided. Do not provide unsupported operational facts.

Use only the supplied context. Convert the information into a concise response brief for emergency decision-makers.

Return valid JSON only, with these exact keys: situationSummary, whyPrioritized, resourceRequirements, routeRecommendation, immediateActions, dataLimitations. immediateActions must be an array of concise strings.`

function fallback(context, error) {
  return { response: generateDeterministicResponse(context), mode: 'fallback', error }
}

export async function generateResponsePlan(context) {
  const apiKey = import.meta.env.VITE_AI_API_KEY
  const apiUrl = import.meta.env.VITE_AI_API_URL
  const model = import.meta.env.VITE_AI_MODEL ?? 'gpt-4.1-mini'

  if (!apiKey || !apiUrl) return fallback(context)

  try {
    const request = await fetch(apiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify({
        model,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: JSON.stringify(context) },
        ],
        response_format: { type: 'json_object' },
      }),
    })
    if (!request.ok) throw new Error(`AI service returned ${request.status}`)
    const payload = await request.json()
    const content = payload.choices?.[0]?.message?.content
    const response = normalizeAiResponse(JSON.parse(content))
    if (!response) throw new Error('AI response did not match the required brief format')
    return { response, mode: 'ai' }
  } catch (error) {
    return fallback(context, error instanceof Error ? error.message : 'AI service unavailable')
  }
}
